### PR TITLE
Remove .vscode

### PR DESCRIPTION
**Pull request by diamonddev01**
Itsd recomended to remove personal config files from your project

### CODE REVIEW

**Comment by tedbrine** [comment]
they aren't personal settings rather makes some formatting restrictions so all developers have the same settings

**Comment by diamonddev01** [comment]
Format on paste and format on save are both entirely personal. I can understand the formatter, however the rest are entirely personal settings

**Review by tedbrine — CHANGES_REQUESTED** [review]
from the comment you just made, you can remove the save on and remove it from the git ignore

**Comment by diamonddev01** [comment]
I'm gonna move this to a new PR for ease

**Pull request closed without merging**
