### PR TITLE
Refactoring and Code Reduction

### PR DESCRIPTION
**Pull request by therealbenpai**
Reduces code by 203 lines
Uses switch statements rather than major if chains
Re-organized to allow for better readability
Fewer vars
Usage of ternaries
Usage of Chalk Template Literals
Singular Error Handler
Combination of both FS packages

### CODE REVIEW

**Comment by therealbenpai** [comment]
@teddybrine if you wanna review this, that should optimise some of the code

**Review by tedbrine — APPROVED** [review]
i'll test rest later

**Comment by camerondevuk** [comment]
Approved.

**Review by tedbrine — APPROVED** [review]
k

**Pull request merged**
